### ISSUE TITLE
SalesForceRest connector createMultipleRecords action is not working

### ISSUE THREAD

**Issue by muthulee** [wso2-ballerina/package-salesforce#4]
erandidesilva commented on May 23, 2017 • 
When $subject is invoked using the given sample the following output came.
[{"errorCode":"NOT_FOUND","message":"The requested resource does not exist"}]

@kesavany
 Member
kesavany commented on Jun 14, 2017 • 
I tried with the API version - v34.0 it is working. But with previous API versions, it resulted the "resource does not exist" error. Could you please try with the version - v34.0.

Original issue - https://github.com/ballerina-lang/connectors/issues/121

**Comment by erandiganepola** [comment]
Solved the issue in code
